config/routes.rb
Rework::Application.routes.draw do
  devise_for :users, :class_name => "Account::User"

  root 'welcome#index'

  get 'dashboard',    to: 'account/dashboard#index',    as: :user_root

  get 'users',  :to => 'users#index',  :as => :search

  resources :users,only: [:index,:show]

  namespace 'account' do
    resource :business_hour,only: [:edit,:update]
    resource :profile      ,only: [:edit,:update]
    resource :contact      ,only: [:edit,:update]
    resource :skill        ,only: [:edit,:update]
  end

  

end

app/models/account.rb
module Account
  def self.table_name_prefix
    'account_'
  end
end

app/models/account/expertise.rb
class Account::Expertise < ActiveRecord::Base
  belongs_to :user
  belongs_to :expertise
end

app/models/account/profile.rb
module Account 
  class FullName
    include Virtus
    attribute :first_name,String
    attribute :last_name,String

    def to_s
      self.first_name + " "  + self.last_name
    end
  end

  class Profile < ActiveRecord::Base
    belongs_to :user,class_name: 'Account::User'

    belongs_to :profession,class_name: 'Job::Profession'

    mount_uploader :photo, PhotoUploader

    def full_name
      FullName.new(first_name: first_name,last_name: last_name)
    end

  end

end

app/models/account/profile_form.rb
module Account
end

app/models/account/skill.rb
module Account
  class Skill < ActiveRecord::Base
    belongs_to :user,class_name: 'Account::User'
    belongs_to :expertise,class_name: 'Job::Expertise'
  end
end

app/models/account/time_range.rb
module Account
  class TimeRange
    include Virtus::ValueObject
    extend ActiveModel::Naming
    include ActiveModel::Conversion
    attribute :start_at,DateTime
    attribute :end_at,DateTime
  end
end

app/models/account/user.rb
module Account
  class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :token_authenticatable, :confirmable,
    # :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable

    has_one :profile,class_name: 'Account::Profile'

    has_many :business_hours ,class_name: 'Account::BusinessHour'

    has_many :skills,class_name: 'Account::Skill'
    has_many :expertises,through: :skills

    before_create :initialize_profile

    before_create :initialize_businss_hours

    def initialize_businss_hours
      Account::BusinessHour.day.values.each do |day|
        self.business_hours.build(day: day)
      end
    end

    def initialize_profile
      self.build_profile
    end

    delegate :update_attributes,:full_name,:photo,:profession, :to => :profile,:prefix => true
  end
end

app/models/job.rb
module Job
  def self.table_name_prefix
    'job_'
  end
end

app/models/job/base.rb
module Job
  class Base < ActiveRecord::Base
    has_ancestry
  end
end

app/models/job/expertise.rb
module Job
  class Expertise < Job::Base
  end
end

app/models/job/field.rb
module Job
  class Field < Job::Base
  end
end

app/models/job/profession.rb
module Job
  class Profession < Job::Base
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = Account::User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = Account::User.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/account/skill_helper.rb
module Account::SkillHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.slim
footer.bs-footer
  p &copy; Takanawa Base,Inc. 2013

app/views/layouts/_navbar.html.slim
div class="navbar navbar-fixed-top navbar-inverse nav-inverse #{"bs-docs-nav" if request.subdomain == 'www'} "
  .container
    button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse"
      - 3.times do
        span class="icon-bar"
    a.navbar-brand.dropdown href="#{root_path}" ReWork
    div class="dropdown"
      ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu"
        li
          a tabindex="-1" href="#" Action
        li
          a tabindex="-1" href="#" Action
        li
          a tabindex="-1" href="#" Action

    div class="nav-collapse collapse bs-navbar-collapse"
      ul.nav.navbar-nav
        ul.nav.navbar-nav.pull-left
      - if signed_in?
        ul.nav.navbar-nav.pull-right
          li= link_to user_root_path do
            i.icon-home.icon-large
          li= link_to destroy_user_session_path,:confirm => 'Are you sure you want to sign out?',:method => :delete do
            i.icon-off.icon-large
      - else
        div class="nav navbar-nav pull-right"
          = link_to(t('sign_in'),  new_user_session_path     ,  class: 'btn  btn-default navbar-btn') 
          = link_to(t('sign_up'),  new_user_registration_path,  class: 'btn btn-default navbar-btn') 

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "ReWork"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    link href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144"
    link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114"
    link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72"
    link href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed"
    link href="favicon.ico" rel="shortcut icon"

  body

    = render 'layouts/navbar'
    .container
      = render 'layouts/header'
      .row
        div class="col-lg-12"
          #content
            = yield
    = render 'layouts/footer'

    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = yield :scripts 
    javascript:
      Rework

app/views/layouts/setting.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "ReWork"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    link href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144"
    link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114"
    link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72"
    link href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed"
    link href="favicon.ico" rel="shortcut icon"
  body

    = render 'layouts/navbar'
    .container
      = render 'layouts/header'
      .row
        .col-lg-3
          .bs-sidebar.affix
            ul.list-group
              li.list-group-item Profile
              ul.list-group-item.nav
                li= link_to 'basic info',edit_account_profile_path
                li= link_to 'contact',edit_account_contact_path
                li= link_to 'availability',edit_account_business_hour_path
                li= link_to 'skills',edit_account_skill_path
              li.list-group-item Account setting
              ul.list-group-item.nav
                li= link_to 'receiving payment',user_root_path
                li= link_to 'payment information',user_root_path
        .col-lg-9
          #content
            = yield
    = render 'layouts/footer'

    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = yield :scripts 
    javascript:
      Rework